### ISSUE TITLE
Hi, my file is of 312 ppi resolution. But when export my assets using this script all images are saved as 72ppi. Please let me know if there is a workaround

### ISSUE THREAD

**Issue by sms007** [jwa107/Photoshop-Export-Layers-to-Files-Fast#101]

**Comment by isadora3** [comment]
Hello, I guess it depends on what you are using the files for. I use this script at least once a week to batch process headshots for print and web. I export them at roughly 4x the size needed for print so that the effective resolution is high enough when I place the images in InDesign. I can then use the same files for web and apply a CSS % to reduce the dimensions. So, to answer your question, two workarounds are:
1- start with a 72dpi photoshop canvas that is 4.34x your final dimensions, which will yield images with an effective resolution of 312dpi when you reduce them to your final dimensions.
2- for an existing file, change the image size to 72dpi without resampling. Then you won't lose quality when they export. 
Hope that helps!

**Comment by jwa107** [comment]
What isadora recommends is probably a good workaround. We don't do anything with ppi intentionally, off-hand I'd say this is something Photoshop natively does through using Save For Web (which is what we are doing under the hood)
