### ISSUE TITLE
Progress bar resource is corrupt?

### ISSUE THREAD

**Issue by maz42** [jwa107/Photoshop-Export-Layers-to-Files-Fast#47]
Having downloaded the latest zip and tried to run it in photoshop cs6 / Yosemite constant error message appears 
![ember library mediator](https://cloud.githubusercontent.com/assets/12460208/7652676/df7c15c4-fb06-11e4-8e70-d62f40aa9edb.png)
(Progress bar resource is corrupt. Please redownload the script with all files)

File looks ok in preview.
Any suggestions?

**Comment by jwa107** [comment]
I'm going to assume you have all the files since you downloaded the zip. Did you make sure to extract the files before running it?

**Comment by maz42** [comment]
Hi,
Yes all files were extracted and then the folder copied into the 
application support folder.
Opening the folder shows meaningful code.
PM

**Comment by skjorn** [comment]
This error basically says that the file is found (present), but its contents couldn't be processed by the Ps API. Since you say that inside of the file looks ok on your PC, a number of subtle issues comes to mind. I removed UTF BOM from the progress bar resource and converted line endings to Unix/Mac, since Windows can deal fine with them. Please re-download and try again if it helps.

Also, tabs could be potentially problematic, but I don't want to remove them unless there's a real need.

**Comment by maz42** [comment]
Today I downloaded the new zip.
It now works as described. 
I need to experiment with it further but thank you very much for your prompt and helpful response.
PM

**Comment by skjorn** [comment]
You're welcome.
