### ISSUE TITLE
Need this to export Layer Groups to JPG

### ISSUE THREAD

**Issue by lucian-marin** [jwa107/Photoshop-Export-Layers-to-Files-Fast#98]
This script seems to be what i need. However the version i tried (found at github.com/jwa107/Photoshop-Export-Layers-to-Files-Fast/arch‌​ive/master.zip) doesn't give me the exact thing i need. I have some experience with Indesign scripting, but none with Photoshop, reason why i am requesting this here.

So, what i have are PSD files with a Background layer at the bottom, then layer groups named as EN, FR, RO, etc, for diffferent languages (up to 20 languages sometimes). These groups may contain one or more text layers and are generally similar, they are just translations of the English layer.

What i need is to export each layer group as a single JPG file using the Background layer as a base artwork each time, and call the pictures as the groups: EN.JPG, FR.JPG, etc.

Thanks

**Comment by jwa107** [comment]
@lucian-marin What version of photoshop are you using?

**Comment by lucian-marin** [comment]
Sorry i should have mentioned, that's CS6, thanks

**Comment by lucian-marin** [comment]
Hi, any change i could get this? Doing a lot of multi-language banners so need a quick export of these. Possibly other people out there needing this. Thanks

**Comment by jwa107** [comment]
@lucian-marin I don't see this being a very high priority at the moment, especially since you can kind of work around this with the existing script already.

What I would do in your case is:

1.  Make a copy of your PSD
2.  Right-click on the group and say "merge group"
3.  Repeat step two for every group
4. Run the script
5. Check the box that says "Lowest layer is background"
6.  Click "Run"

This will give you your desired result, without a script change.
Again, make sure you make a copy first so you don't accidentally save the merged file over the original.

**Comment by lucian-marin** [comment]
It sort of works, but i still need to click 'Merge Group' 20 times per banner, then these are saved as 01, 02, 03.jpg which in turn needs 20 rename operations to turn them into EN.jpg, ES.jpg and etc, also it is confusing to follow which number represented each group so possibly mixing languages. So not really that useful, but thanks for your time.

**Comment by jwa107** [comment]
@lucian-marin If you renamed the merged layers as you went you wouldn't have the issue of trying to remember what was what after the export.

Of course this isn't as convenient as if the script had all that built-in, I'm just offering a workaround that would be faster than doing _everything_ by hand for the time that the script _can't_ do what you need it to.
